name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: PHP_CodeSniffer Check with Annotations
        uses: chekalsky/phpcs-action@v1.2.0
