name: Test PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Check Directories
        run: ls -la
