name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: PHP_CodeSniffer Check with Annotations
      uses: chekalsky/phpcs-action@v1.2.0
