name: Test PHPCS

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: PHP_CodeSniffer Check with Annotations
        uses: chekalsky/phpcs-action@v1.2.0
        with:
          enable_warnings: true
