name: PHP Code Sniffer

on:
  push:
    branches: [ master, development ]
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    branches: [ master, development ]
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Composer Install
        run: composer install --dev --prefer-dist --no-progress --no-suggest

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
          phpcs_bin_path: './vendor/bin/phpcs'