name: PHP Code Sniffer

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Composer Install
        uses: nanasess/composer-installer-action@master
      - run: coposer install

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true

      # - name: PHP_CodeSniffer Check with Annotations
      #   uses: chekalsky/phpcs-action@v1.2.0
      #   with:
      #     enable_warnings: true
