name: PHP Code Sniffer

on:
  push:
    branches: [ master, development ]
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    branches: [ master, development ]
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true

      # - name: PHP_CodeSniffer Check with Annotations
      #   uses: chekalsky/phpcs-action@v1.2.0
      #   with:
      #     enable_warnings: true
